2023-06-20 16:13:12 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Acer Nitro 5/IdeaProjects/goit.jdbc.flyway.CRUD/database_test2.mv.db [2.1.212/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Acer Nitro 5/IdeaProjects/goit.jdbc.flyway.CRUD/database_test2.mv.db [2.1.212/7]" [50000-212]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:124)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3349)
	at org.h2.mvstore.MVStore.panic(MVStore.java:590)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:466)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4118)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:258)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:223)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:48)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:74)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:134)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:140)
	at goit.jdbc.crud.project.DatabaseInitService.initDb(DatabaseInitService.java:8)
	at goit.jdbc.crud.project.Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Acer Nitro 5/IdeaProjects/goit.jdbc.flyway.CRUD/database_test2.mv.db [2.1.212/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Acer Nitro 5/IdeaProjects/goit.jdbc.flyway.CRUD/database_test2.mv.db [2.1.212/7]" [50000-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 23 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Acer Nitro 5/IdeaProjects/goit.jdbc.flyway.CRUD/database_test2.mv.db [2.1.212/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:449)
	... 17 more
2023-06-20 16:13:36 jdbc[3]: null
org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-214]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:190)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:132)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:288)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:808)
	at org.h2.server.web.WebApp.login(WebApp.java:1033)
	at org.h2.server.web.WebApp.process(WebApp.java:226)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:176)
	at org.h2.server.web.WebThread.process(WebThread.java:152)
	at org.h2.server.web.WebThread.run(WebThread.java:101)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:678)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 13 more
2023-06-20 16:14:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "[*]PROJECT_WORKER"; ожидалось "PREPARE"
Syntax error in SQL statement "[*]PROJECT_WORKER"; expected "PREPARE"; SQL statement:
PROJECT_WORKER [42001-214]
2023-06-21 12:28:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "[*]INCERT INTO client (name) VALUES ? "; ожидалось "INSERT"
Syntax error in SQL statement "[*]INCERT INTO client (name) VALUES ? "; expected "INSERT"; SQL statement:
INCERT INTO client (name) VALUES ?  [42001-212]
2023-06-21 12:30:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "[*]INCERT INTO client (name) VALUES (?) "; ожидалось "INSERT"
Syntax error in SQL statement "[*]INCERT INTO client (name) VALUES (?) "; expected "INSERT"; SQL statement:
INCERT INTO client (name) VALUES (?)  [42001-212]
2023-06-21 12:31:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Метод разрешен только для запросов. Используйте execute или executeUpdate вместо executeQuery
Method is only allowed for a query. Use execute or executeUpdate instead of executeQuery; SQL statement:
INSERT INTO client (name) VALUES (?) [90002-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.command.Prepared.query(Prepared.java:235)
	at org.h2.command.CommandContainer.query(CommandContainer.java:256)
	at org.h2.command.Command.executeQuery(Command.java:190)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:128)
	at goit.jdbc.crud.project.DAO.ClientService.create(ClientService.java:39)
	at goit.jdbc.crud.project.Main.main(Main.java:15)
2023-06-21 12:47:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Данный метод не разрешен для PreparedStatement; используйте Statement.
This method is not allowed for a prepared statement; use a regular statement instead. [90130-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:303)
	at goit.jdbc.crud.project.DAO.ClientService.create(ClientService.java:42)
	at goit.jdbc.crud.project.Main.main(Main.java:15)
2023-06-21 12:51:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Данный метод не разрешен для PreparedStatement; используйте Statement.
This method is not allowed for a prepared statement; use a regular statement instead. [90130-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:303)
	at goit.jdbc.crud.project.DAO.ClientService.create(ClientService.java:42)
	at goit.jdbc.crud.project.Main.main(Main.java:15)
2023-06-21 13:26:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Столбец "id" не найден
Column "id" not found [42122-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3518)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:745)
	at goit.jdbc.crud.project.DAO.ClientService.getMaxId(ClientService.java:58)
	at goit.jdbc.crud.project.DAO.ClientService.create(ClientService.java:33)
	at goit.jdbc.crud.project.Main.main(Main.java:15)
2023-06-21 13:27:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Столбец "id" не найден
Column "id" not found [42122-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3518)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:745)
	at goit.jdbc.crud.project.DAO.ClientService.getMaxId(ClientService.java:58)
	at goit.jdbc.crud.project.DAO.ClientService.create(ClientService.java:33)
	at goit.jdbc.crud.project.Main.main(Main.java:15)
2023-06-21 13:27:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Столбец "id" не найден
Column "id" not found [42122-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3518)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:745)
	at goit.jdbc.crud.project.DAO.ClientService.getMaxId(ClientService.java:58)
	at goit.jdbc.crud.project.DAO.ClientService.create(ClientService.java:33)
	at goit.jdbc.crud.project.Main.main(Main.java:15)
2023-06-21 13:29:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "[*]DELET from CLIENT Where id=10"; ожидалось "DELETE, DROP, DECLARE, DEALLOCATE"
Syntax error in SQL statement "[*]DELET from CLIENT Where id=10"; expected "DELETE, DROP, DECLARE, DEALLOCATE"; SQL statement:
DELET from CLIENT Where id=10 [42001-214]
2023-06-21 13:44:04 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Acer Nitro 5/IdeaProjects/goit.jdbc.flyway.CRUD/database_test2.mv.db [2.1.212/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Acer Nitro 5/IdeaProjects/goit.jdbc.flyway.CRUD/database_test2.mv.db [2.1.212/7]" [50000-212]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:124)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3349)
	at org.h2.mvstore.MVStore.panic(MVStore.java:590)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:466)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4118)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at goit.jdbc.crud.project.srorage.ConectionProvider.<init>(ConectionProvider.java:15)
	at goit.jdbc.crud.project.srorage.ConectionProvider.getInstance(ConectionProvider.java:24)
	at goit.jdbc.crud.project.DAO.ClientService.getById(ClientService.java:32)
	at goit.jdbc.crud.project.Main.main(Main.java:15)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Acer Nitro 5/IdeaProjects/goit.jdbc.flyway.CRUD/database_test2.mv.db [2.1.212/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Acer Nitro 5/IdeaProjects/goit.jdbc.flyway.CRUD/database_test2.mv.db [2.1.212/7]" [50000-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 21 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Acer Nitro 5/IdeaProjects/goit.jdbc.flyway.CRUD/database_test2.mv.db [2.1.212/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:449)
	... 15 more
2023-06-21 13:44:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Столбец "MANE" не найден
Column "MANE" not found; SQL statement:
SELECT mane FROM client WHERE id=(?) [42122-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:244)
	at org.h2.expression.ExpressionColumn.optimizeOther(ExpressionColumn.java:226)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:213)
	at org.h2.command.query.Select.prepareExpressions(Select.java:1170)
	at org.h2.command.query.Query.prepare(Query.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:574)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at goit.jdbc.crud.project.DAO.ClientService.getById(ClientService.java:33)
	at goit.jdbc.crud.project.Main.main(Main.java:15)
2023-06-21 13:44:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Параметр "#1" не установлен
Parameter "#1" is not set; SQL statement:
SELECT name FROM client WHERE id=(?) [90012-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:646)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.Parameter.checkSet(Parameter.java:75)
	at org.h2.command.Prepared.checkParameters(Prepared.java:186)
	at org.h2.command.CommandContainer.query(CommandContainer.java:255)
	at org.h2.command.Command.executeQuery(Command.java:190)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:128)
	at goit.jdbc.crud.project.DAO.ClientService.getById(ClientService.java:34)
	at goit.jdbc.crud.project.Main.main(Main.java:15)
2023-06-21 13:45:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Параметр "#1" не установлен
Parameter "#1" is not set; SQL statement:
SELECT name FROM client WHERE id=(?) [90012-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:646)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.Parameter.checkSet(Parameter.java:75)
	at org.h2.command.Prepared.checkParameters(Prepared.java:186)
	at org.h2.command.CommandContainer.query(CommandContainer.java:255)
	at org.h2.command.Command.executeQuery(Command.java:190)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:128)
	at goit.jdbc.crud.project.DAO.ClientService.getById(ClientService.java:34)
	at goit.jdbc.crud.project.Main.main(Main.java:15)
2023-06-21 13:45:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Параметр "#1" не установлен
Parameter "#1" is not set; SQL statement:
SELECT name FROM client WHERE id=(?) [90012-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:646)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.Parameter.checkSet(Parameter.java:75)
	at org.h2.command.Prepared.checkParameters(Prepared.java:186)
	at org.h2.command.CommandContainer.query(CommandContainer.java:255)
	at org.h2.command.Command.executeQuery(Command.java:190)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:128)
	at goit.jdbc.crud.project.DAO.ClientService.getById(ClientService.java:34)
	at goit.jdbc.crud.project.Main.main(Main.java:15)
2023-06-21 14:30:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Столбец "MANE" не найден
Column "MANE" not found; SQL statement:
 UPDATE client SET mane =(?) WHERE id=(?) [42122-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:754)
	at org.h2.command.Parser.readTableColumn(Parser.java:1092)
	at org.h2.command.Parser.readUpdateSetClause(Parser.java:1159)
	at org.h2.command.Parser.parseUpdate(Parser.java:1128)
	at org.h2.command.Parser.parsePrepared(Parser.java:858)
	at org.h2.command.Parser.parse(Parser.java:691)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:568)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at goit.jdbc.crud.project.DAO.ClientService.setName(ClientService.java:35)
	at goit.jdbc.crud.project.Main.main(Main.java:17)
2023-06-21 14:31:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "[*]elect * from CLIENT"; ожидалось "EXPLAIN, EXECUTE"
Syntax error in SQL statement "[*]elect * from CLIENT"; expected "EXPLAIN, EXECUTE"; SQL statement:
elect * from CLIENT [42001-214]
2023-06-21 14:32:28 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Acer Nitro 5/IdeaProjects/goit.jdbc.flyway.CRUD/database_test2.mv.db [2.1.212/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Acer Nitro 5/IdeaProjects/goit.jdbc.flyway.CRUD/database_test2.mv.db [2.1.212/7]" [50000-212]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:124)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3349)
	at org.h2.mvstore.MVStore.panic(MVStore.java:590)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:466)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4118)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at goit.jdbc.crud.project.srorage.ConectionProvider.<init>(ConectionProvider.java:15)
	at goit.jdbc.crud.project.srorage.ConectionProvider.getInstance(ConectionProvider.java:24)
	at goit.jdbc.crud.project.DAO.ClientService.setName(ClientService.java:34)
	at goit.jdbc.crud.project.Main.main(Main.java:17)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Acer Nitro 5/IdeaProjects/goit.jdbc.flyway.CRUD/database_test2.mv.db [2.1.212/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Acer Nitro 5/IdeaProjects/goit.jdbc.flyway.CRUD/database_test2.mv.db [2.1.212/7]" [50000-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 21 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Acer Nitro 5/IdeaProjects/goit.jdbc.flyway.CRUD/database_test2.mv.db [2.1.212/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:449)
	... 15 more
2023-06-21 15:26:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "SELECT * [*]name FROM client"
Syntax error in SQL statement "SELECT * [*]name FROM client"; SQL statement:
SELECT * name FROM client [42000-212]
